### ISSUE TITLE
Can't get rid of links below the submit button individually.

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/colorlib-login-customizer#62]

**Comment by puikinsh** [comment]
Thanks for the suggestion, and apologies for the very long delay here.

Since this was filed, the plugin gained a **Hide Extra Links** toggle (under the Form Texts section) that shows/hides the links below the login form. It's currently all-or-nothing rather than per-link, but you can hide any single link today using the **Custom CSS** box in the Customizer, since each link has its own selector:

```css
/* Hide just "Lost your password?" */
#clc-lost-password-text { display: none; }

/* Hide just the Register link */
#register-link-label { display: none; }

/* Hide just "Back to site" */
#backtoblog { display: none; }
```

Because there's a working approach for individual control and a global toggle for the common case, I'm closing this old request to keep the tracker tidy. If you'd genuinely like dedicated per-link checkboxes in the UI on the current 2.1.1, please reopen or open a fresh issue and we'll consider it. Thanks again!
